apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gcr.io/personal-285812/barcade-backend
          ports:
            - containerPort: 5001
          env:
            - name: DB_IP
              value: 10.104.7.45
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: 7(Jz_L`9HpTWDmxj
            - name: OPENAI_API_KEY
              value: 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

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
